project_id = "kxqrlshnhcorekeafqws"

[functions.get-place-reviews]
verify_jwt = true

[functions.generate-restaurant-image]
verify_jwt = true

[functions.text-to-speech]
verify_jwt = true

[functions.fetch-rio-security-data]
verify_jwt = true

[functions.translate-tourist-spot]
verify_jwt = true